language: python
cache: pip
python:
  - "3.5"

# command to install dependencies
install:
  - pip install -e .[testing]

# command to run tests
script:
  - nosetests --with-coverage

after_success:
  - coveralls

